# -*- coding: utf-8 -*-
"""Self_Driving_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m0q6yMxYnrSZttnfJ8sblnMiaqqKInn9
"""

import math
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow import keras

!pip install utils

import cv2
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from skimage import util, exposure
from sklearn.utils import shuffle
from tensorflow.keras import models, layers

from google.colab import files
uploaded = files.upload()

input_shape = (160, 320, 3)
dropout = 0.25

m = models.Sequential()
m.add(layers.Lambda(lambda x: x/255.0-0.5,input_shape=input_shape))
m.add(layers.Cropping2D(cropping=((70,25), (0,0))))
m.add(layers.Convolution2D(24,5,2,activation='relu'))
m.add(layers.Convolution2D(36,5,2,activation='relu'))
m.add(layers.Convolution2D(48,5,2,activation='relu'))
m.add(layers.Dropout(dropout))
m.add(layers.Convolution2D(64,3,activation='relu'))
m.add(layers.Convolution2D(64,3,activation='relu'))
m.add(layers.Flatten())
m.add(layers.Dense(100))
m.add(layers.Dropout(dropout))
m.add(layers.Dense(50))
m.add(layers.Dense(10))
m.add(layers.Dense(1))

data = pd.read_csv('driving_log.csv')

data.head(10)

!ls

m.load_weights('model.h5')

m.summary()

from PIL import Image
from numpy import asarray

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = mpimg.imread('center_2021_12_27_13_43_54_283.jpg')

imgplot = plt.imshow(img)

img = Image.open('center_2021_12_27_13_43_54_283.jpg')

test = asarray(img)

test.shape

import utils

test = np.array([test])

m.predict(test)